### ISSUE TITLE
301 redirects not working on 7.2

### ISSUE THREAD

**Issue by jonathanS8080** [kipusoep/UrlTracker#62]
Hi,
We have installed the URL Tracker onto our Umbraco 7.2 and it doesnt seem to redirect.
We set up an old url, for example /blog/ and set the new url to a node id in the site, for arguments sake, 1074. When we test the old url it takes us to a 404 error page. We have also tried manually entering the RedirectURL and still it takes us to the 404 page.
We have added the settings in the Webconfig as described in the Projects page.
Each url redirect entry appears in the icUrlTracker database table.
We did notice that if you delete a url rewrite it doesnt remove it from the database. One test we did it actually added the entry in again after we deleted it.
Any ideas on what we need to do - does it use a config file (apart from the webconfig)?

Thanks in advance,
Jon

**Comment by kipusoep** [comment]
* What version of the Url Tracker?
* Do you have any hostnames configured in umbraco? Which?

**Comment by jonathanS8080** [comment]
Hi,
It is package version 3.4.
How would you find which Hostnames you have set up in Umbraco?

Thanks
Jon

**Comment by jonathanS8080** [comment]
Hi,
If you are referring to Hostnames in the Admin section then we haven't set any up,

Jon

**Comment by kipusoep** [comment]
Yes I mean this:

![image](https://cloud.githubusercontent.com/assets/1866549/6130767/a771a332-b147-11e4-8c15-6757ab2f968e.png)
![image](https://cloud.githubusercontent.com/assets/1866549/6130770/ac931ca6-b147-11e4-8038-77f932a5980b.png)

**Comment by jonathanS8080** [comment]
Hi, 
Thanks for that - no we haven't set any up,

Jon

**Comment by jonathanS8080** [comment]
Hi, any updates to your thoughts? Jon

**Comment by kipusoep** [comment]
No not yet. Maybe you can provide some screenshots of the Url Tracker UI to see what kind or redirects you've created?

**Comment by jonathanS8080** [comment]
Hi, the only one I have done is OldUrl: /blog/
New Url: /newsblog/

**Comment by kipusoep** [comment]
I've been able to reproduce. It's a bug introduced by #40 I think.
Let me check with Sandro about this, I'll get back to you soon.

**Comment by leethomascook** [comment]
Any news on this issue?

**Comment by kipusoep** [comment]
No, if there was I would have said so, right?

**Comment by KirschnerMatt** [comment]
Using 3.3 here and I have no hostname in Umbraco set. It works just fine for me. 

@jonathan, perhaps you could uninstall and go back a version for now?

**Comment by kipusoep** [comment]
Yes I can confirm this bug was introduced in v3.4 because of #40

**Comment by justinbhayes** [comment]
I am having the same issue after upgrading my site to 7.2.1 and installing the UrlTracker version 3.4. All of my previous 301 redirects now throw a 404. Is there a way to roll back to version 3.3?

**Comment by justinbhayes** [comment]
Sounds great. Thanks.

**Comment by kipusoep** [comment]
This is fixed in v3.5, which I'll release in a few.

**Comment by justinbhayes** [comment]
My redirects are still not working after upgrading. Are there any additional steps besides uninstalling 3.4 and upgrading to 3.5 for UrlTracker to work?

**Comment by kipusoep** [comment]
No that should be it. Could you post the entire SQL row of the redirect you mentioned?

**Comment by justinbhayes** [comment]
These are the contents of a row:

Id=1474965	
OldUrl=recipe-category/30-minutes-or-less-recipes
OldUrlQueryString=NULL
OldRegex=NULL
RedirectRootNodeId=1055
RedirectNodeId=NULL
RedirectUrl=recipes
RedirectHttpCode=301
RedirectPassThroughQueryString=1
Notes=Fixing Legacy 404
Is404=0
Referrer=NULL	
Inserted=2015-01-21 19:25:42.397
ForceRedirect=1

Also, if I click Advanced view in any redirect setup in UrlTracker, I get this error: Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: 'ddlRootNode' has a SelectedValue which is invalid because it does not exist in the list of items. Parameter name: value

**Comment by kipusoep** [comment]
Is there a node with id 1055?

**Comment by justinbhayes** [comment]
Yes, but it's a different page than the redirect url is supposed to go to.

**Comment by kipusoep** [comment]
I know, but it's the redirect ROOT node id, not the redirect id.
Could you create a screenshot of the umbraco tree and highlight the redirect id node and the redirect root id node?

**Comment by justinbhayes** [comment]
![contenttree](https://cloud.githubusercontent.com/assets/399601/6290091/0fcdb14c-b8ea-11e4-8ea0-989f9ca94401.png)

**Comment by justinbhayes** [comment]
Did I answer your question correctly? Redirects are still not working for me.

**Comment by kipusoep** [comment]
Yes you did.

**Comment by stephant33** [comment]
I had the same issue Sorry for not reading this thread earlier I went from 3.4 to 3.5 using umbraco 7.0 and all of my redirects quit working. All I get now are 404 errors as well.

**Comment by gnokto** [comment]
Hi there,  I had to downgrade version from 3.5 to 3.3 for manual redirects to work again. The issue on this version is that old urls with extension .html for example don't work. No error page, the page just goes blank.

**Comment by kipusoep** [comment]
Thanks @gnokto, I hope I can look into this today.

**Comment by kipusoep** [comment]
I am unable to reproduce this :-(
Could you tell me what the output of the logs is when you enable it and request an 'Old URL'?

Instructions to enable logging:
* Add an appSetting to your web.config: ```<add key="urlTracker:enableLogging" value="true"/>```
* In 'config\log4net.config', change the root logger priority to 'Debug' instead of 'Info': ```<priority value="Debug"/>```

The lines I'm interested in contain "InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper".

**Comment by mschraeder** [comment]
I'm having the same issue. 

Umbraco 7.2.5
UrlTracker 3.7

Used to work great (on other sites), now its just doing nothing.

**Comment by kipusoep** [comment]
@mschraeder Please look at the comment I left above yours. To fix this I need more information.
