### ISSUE TITLE
Issue:  Upgraded URL Tracker From 3.4 to 3.5 using umbraco 7.0

### ISSUE THREAD

**Issue by stephant33** [kipusoep/UrlTracker#67]
I have upgraded form 3.4 to 3.5 and now none of my pages will redirect.  I now get 404 errors.
Not sure if I am missing a step.

**Comment by stephant33** [comment]
I am also getting this error when I click advanced view.

![image](https://cloud.githubusercontent.com/assets/11276249/6447630/9587f882-c0d9-11e4-93db-50855e91cbf1.png)

**Comment by justinbhayes** [comment]
Is there any update on this issue? I too am running 3.5 and none of my redirects are working. When I click on Advanced View when viewing any redirect I have setup, I also get this error:

Sys.WebForms.PageRequestManagerServerErrorException: Sys.WebForms.PageRequestManagerServerErrorException: 'ddlRootNode' has a SelectedValue which is invalid because it does not exist in the list of items.

Parameter name: value

**Comment by kipusoep** [comment]
No. You're more than welcome to look into this bug yourself though.

**Comment by stephant33** [comment]
Hi Stef,

I was hoping for some insight, on why the upgrade to 3.4 to 3.5 would stop the redirects from working?  And I am left with 404 page errors.  I would really appreciate any feedback. It's a great tool and I appreciate all the work that has been done.  Thank you - ST

**Comment by kipusoep** [comment]
You're always free to downgrade to an earlier version, I've got other stuff on my mind at the moment.

**Comment by stephant33** [comment]
Okay no worries. - 
 Hartelijk Bedankt,  
Stephan

**Comment by justinbhayes** [comment]
Do you have instructions on how to downgrade?

**Comment by kipusoep** [comment]
Doesn't really matter, as long as the assembly is being replaced with the older version.

**Comment by justinbhayes** [comment]
Do you host the assembly for all previous versions somewhere? I only see 3 releases here: https://github.com/kipusoep/UrlTracker/releases

**Comment by stephant33** [comment]
Well this is what I ended up doing but I am running !!!7.0!!! 

1. Went to https://our.umbraco.org/projects/developer-tools/301-url-tracker
2. Scrolled down to the bottom of the page ->  Clicked the Archived Files Link
3. Downloaded Url_Tracker_2.6.2.zip
4. Logged into Umbraco
5. Uninstalled 3.5 URL Tracker
6. Installed Local: Package Url_Tracker_2.6.2.zip
![image](https://cloud.githubusercontent.com/assets/11276249/6605969/37ac1984-c802-11e4-9a2d-6c05ffd5eee0.png)
7.  Everything started working "properly"  Meaning the no more 404 errors or the error I described above about the advanced view.
8.  I did this on my test server before I doing it in production.   
9.  I am curious why there is not a 3.4 version available?  And can I install the versions from
https://github.com/kipusoep/UrlTracker/releases ?

Again, I appreciate any help moving forward.  Stefan, I know you are very busy person and please forgive my ignorance.  

Merci,

Stephan

**Comment by UmbracoNewb** [comment]
Looks like it would be a wise decision to stop using this plugin, if support is closed down. 
For those with issues with 3.5, here is what you do:
- Leave the 3.5 installed or install it if you haven't
- Overwrite the 3.5 files in /bin, with the 3.3 files from this zip: https://dl.dropboxusercontent.com/u/18102/URL_Tracker_33.zip
- Start looking for an alternative

**Comment by kipusoep** [comment]
@UmbracoNewb Thanks for the great comment, really!
Nobody said support is closed down. Why would you say something like this?! It's okay if you stop using this plug-in, but stop encouraging others to do the same.
I've put many many work into this plug-in and I won't let you ruin it for me and other Umbraco enthousiasts.

**Comment by UmbracoNewb** [comment]
First, let me say that I use the plugin and find it very useful and that is why I would hate to see it die. My concern is that when you state something like:
>> You're more than welcome to look into this bug yourself though.
>> You're always free to downgrade to an earlier version, I've got other stuff on my mind at the moment.
then how could the community think otherwise, than the product is closing down? 
If support is closed and further development is closed down, then the product will break with future Umbraco versions. I would rather have a supported product ready by hand when that happens.

If the product is still supported and further development is happening, then hurray for that, I will continue to use it. I hope you see my point, cause I didn't intend to start a flame war.

**Comment by kipusoep** [comment]
@UmbracoNewb 
"*You're more than welcome to look into this bug yourself though*" --> It's always easy to create a bug report and let someone else fix it, without even looking into it yourself.
"*You're always free to downgrade to an earlier version, I've got other stuff on my mind at the moment*" --> I don't have the time **at the moment**, so it might be an idea to downgrade to version 3.4 for instance.

Anyway, let's stop the discussion right now, because it's based on a misunderstanding.

Ontopic:
It's my fault there aren't any earlier version available. I should've tagged the releases here on Github.
Luckily I have some previous versions still on my PC and I've uploaded them for you:
https://our.umbraco.org/projects/developer-tools/301-url-tracker (Archived Files).

**Comment by UmbracoNewb** [comment]
Agreed and thanks for the archived files :-)

I ran into the same problem as stephant33 and I made a fresh installment, not a redirect. Have replaced the binaries with 3.3 and that solved it.

**Comment by justinbhayes** [comment]
Thanks for the help @UmbracoNewb, however replacing the 2 bin files didn't work for me. My redirects still are not working, but I am now able to open Advanced View. Were there any other steps besides replacing the 2 files to get UrlTracker working again?

**Comment by kipusoep** [comment]
Which version(s) have you tried @justinbhayes?

**Comment by justinbhayes** [comment]
I have tried 3.3, 3.4 and 3.5 with no success. Currently running 3.3 now. The last time Url Tracker worked for me was when I was running version 2.6.1 on Umbraco 6.2.1. After upgrading to Umbraco 7.2.1, I haven't been able to get Url Tracker working.

**Comment by kipusoep** [comment]
It seems @stephant33 has issues with v3.5 only, while everything was working fine with v3.4. It seems your (@justinbhayes) issue is something else?

**Comment by justinbhayes** [comment]
Perhaps, but as noted in a different issue (https://github.com/kipusoep/UrlTracker/issues/62), another user was having issues with 3.4 as well.

**Comment by kipusoep** [comment]
I'll need some time to test the functionality better.

**Comment by stephant33** [comment]
I am pretty sure the functionality for 3.4 worked fine for me in Umbraco 7.0. I will try to install 3.4 on my test server again and let you know.

**Comment by kipusoep** [comment]
I hope I can look into this today.

**Comment by kipusoep** [comment]
I am unable to reproduce this :-(
Could you tell me what the output of the logs is when you enable it and request an 'Old URL'?

Instructions to enable logging:
* Add an appSetting to your web.config: ```<add key="urlTracker:enableLogging" value="true"/>```
* In 'config\log4net.config', change the root logger priority to 'Debug' instead of 'Info': ```<priority value="Debug"/>```

The lines I'm interested in contain "InfoCaster.Umbraco.UrlTracker.Helpers.LoggingHelper".

**Comment by justinbhayes** [comment]
I am embarrassed to report that I had urlTracker disabled in the web.config. We had so many issues with it in version 2.6.1, I forgot to enable it after upgrading.

On another note, we found that we needed to disable tracking for urlTracker as it added a million rows of 404's to a database table that grew too large over time. This happened when the load balancer pinged a url that didn't exist on each server.

Thanks for all of your help @kipusoep !

urlTracker is back working for me. :)

**Comment by kipusoep** [comment]
@justinbhayes That's good to hear! Did you know you can disable 404 tracking only? It's in the readme ;-) Look for "urlTracker:notFoundTrackingDisabled" :+1:

**Comment by justinbhayes** [comment]
Yup. We have it disabled. Thanks again.

**Comment by kipusoep** [comment]
Could you try again with v3.8, which I just released?

**Comment by stephant33** [comment]
Yes I will this weekend. 

Thanks

ST

**Comment by justinbhayes** [comment]
I can confirm that after upgrading Courier to 3.8 that all of my redirects work again.

However, I do still get an error when clicking Advanced View within any of the redirect rules.

**Comment by kipusoep** [comment]
The error means that the dropdownlist is bound to the list of currently configured domains, but it seems there are redirects with a root node id which is not a domain (anymore?).
Could you check this yourself via SQL for example, please?

**Comment by kipusoep** [comment]
Closing this for now, if there are any issues left, please open a new ticket.
